openapi: 3.0.3
info:
  title: Smart Home SDK - Models shared across smart home services
  description: Smart Home SDK
  version: 1.0.0

tags:
  - name: Smart Home
    description: SDK Smart Home

paths: {}

components:
  schemas:
    RoomName:
      type: string
      enum:
        - "Wardrobe"
        - "Bedroom"
        - "Livia"
        - "Tobi"
        - "Office"
        - "BathroomUp"
        - "HallUp"
        - "Stairs"
        - "Kitchen"
        - "LivingRoom"
        - "Cinema"
        - "HallDown"
        - "BathroomDown"
        - "Entrance"
        - "Garage"
        - "Boiler"
        - "Garden"
        - "Sauna"
        - "Sanctum"
    IotType:
      type: string
      enum:
        - "Shelly"
        - "Eaton"
        - "Other"
    EatonGateway:
      type: string
      enum:
        - "Blinds"
        - "Light"