openapi: 3.0.3
info:
  title: Smart Home SDK - Models shared across smart home services
  description: Smart Home SDK
  version: 1.0.0

tags:
  - name: Smart Home
    description: SDK Smart Home

paths: {}

components:
  schemas:
    RoomName:
      type: string
      enum:
        - "Loft"
        - "Wardrobe"
        - "Bedroom"
        - "Livia"
        - "Tobi"
        - "Office"
        - "BathroomUp"
        - "HallUp"
        - "Stairs"
        - "Kitchen"
        - "LivingRoom"
        - "Cinema"
        - "HallDown"
        - "BathroomDown"
        - "Entrance"
        - "Garage"
        - "Boiler"
        - "Garden"
        - "Sauna"
        - "Sanctum"
    IotVendor:
      type: string
      enum:
        - "Shelly"
        - "Eaton"
        - "Other"
    EatonGateway:
      type: string
      enum:
        - "Blinds"
        - "Lights"
    DeviceType:
      type: string
      enum:
        - "TemperatureSensor"
        - "Blinds"
        - "Light"
        - "Dimmer"
    EatonConfiguration:
      type: object
      properties:
        dataPoint:
          minimum: 1
          maximum: 99
          type: integer
        eatonGateway:
          $ref: '#/components/schemas/EatonGateway'
    ShellyConfiguration:
      type: object
      properties:
        address:
          type: string
          pattern: '^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$'