openapi: 3.0.3
info:
  title: Smart Home SDK - Models shared across smart home services
  description: Smart Home SDK
  version: 1.0.0

tags:
  - name: Smart Home
    description: SDK Smart Home

paths: {}

components:
  schemas:
    RoomName:
      type: string
      enum:
        - "loft"
        - "wardrobe"
        - "bedroom"
        - "livia"
        - "tobi"
        - "office"
        - "bathroom up"
        - "hall_up"
        - "stairs"
        - "kitchen"
        - "living room"
        - "cinema"
        - "hall down"
        - "bathroom down"
        - "entrance"
        - "garage"
        - "boiler"
        - "garden"
        - "sauna"
        - "sanctum"

    SystemActiveReply:
      type: object
      required:
        - active
      properties:
        active:
          type: boolean
          description: Indicates if the system is active
