openapi: 3.0.3
info:
  title: Smart Home SDK - Models shared across smart home services
  description: Smart Home SDK
  version: 1.0.0

tags:
  - name: Smart Home
    description: SDK Smart Home

paths: {}

components:
  schemas:
    RoomName:
      type: string
      enum:
        - "loft"
        - "wardrobe"
        - "bedroom"
        - "livia"
        - "tobi"
        - "office"
        - "bathroom_up"
        - "hall_up"
        - "stairs"
        - "kitchen"
        - "living_room"
        - "cinema"
        - "hall_down"
        - "bathroom_down"
        - "entrance"
        - "garage"
        - "boiler"
        - "garden"
        - "sauna"
        - "sanctum"
    IotVendor:
      type: string
      enum:
        - "shelly"
        - "eaton"
        - "other"
    EatonGateway:
      type: string
      enum:
        - "blinds"
        - "lights"
    DeviceConfiguration:
      type: object
      properties:
        eatonConfiguration:
          $ref: '#/components/schemas/EatonConfiguration'
        shellyConfiguration:
          $ref: '#/components/schemas/ShellyConfiguration'
    DeviceConfigurationRequest:
      type: object
      required:
        - roomName
        - iotVendor
        - deviceConfiguration
      properties:
        roomName:
          type: string
          minLength: 3
          maxLength: 20
          nullable: false
          x-field-extra-annotation: "@NotEmpty"
        iotVendor:
          type: string
          minLength: 3
          maxLength: 20
        deviceType:
          type: string
          minLength: 3
          maxLength: 20
        deviceConfiguration:
          $ref: '#/components/schemas/DeviceConfiguration'
    DeviceType:
      type: string
      enum:
        - "temperature_sensor"
        - "blinds"
        - "light"
        - "dimmer"
    EatonDataPoint:
      type: integer
      minimum: 1
      maximum: 99
    EatonConfiguration:
      type: object
      properties:
        dataPoint:
          $ref: '#/components/schemas/EatonDataPoint'
        eatonGateway:
          $ref: '#/components/schemas/EatonGateway'
    EatonConfigurationResponse:
      type: object
      properties:
        dataPoint:
          $ref: '#/components/schemas/EatonDataPoint'
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        roomName:
          $ref: '#/components/schemas/RoomName'
    ShellyConfiguration:
      type: object
      properties:
        address:
          type: string
          pattern: '^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$'
    DeviceStatusUpdate:
      type: object
      properties:
        roomName:
          $ref: '#/components/schemas/RoomName'
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        value:
          type: string
      required:
        - roomName
        - deviceType
        - value
    EatonStatusReply:
      type: object
      required:
        - gateway
        - message
      properties:
        gateway:
          $ref: '#/components/schemas/EatonGateway'
        message:
          type: string
          pattern: '^5A(,[0-9A-Fa-f]{1,2}){8,18},A5$'
    EatonStatusResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
