openapi: 3.0.3
info:
  title: Smart Home SDK - Models shared across smart home services
  description: Smart Home SDK
  version: 1.0.0

tags:
  - name: Smart Home
    description: SDK Smart Home

paths: {}

components:
  schemas:
    RoomName:
      type: string
      enum:
        - "Loft"
        - "Wardrobe"
        - "Bedroom"
        - "Livia"
        - "Tobi"
        - "Office"
        - "BathroomUp"
        - "HallUp"
        - "Stairs"
        - "Kitchen"
        - "LivingRoom"
        - "Cinema"
        - "HallDown"
        - "BathroomDown"
        - "Entrance"
        - "Garage"
        - "Boiler"
        - "Garden"
        - "Sauna"
        - "Sanctum"
    IotVendor:
      type: string
      enum:
        - "Shelly"
        - "Eaton"
        - "Other"
    EatonGateway:
      type: string
      enum:
        - "Blinds"
        - "Lights"
    DeviceConfiguration:
      type: object
      properties:
        eatonConfiguration:
          $ref: '#/components/schemas/EatonConfiguration'
        shellyConfiguration:
          $ref: '#/components/schemas/ShellyConfiguration'
    DeviceConfigurationRequest:
      type: object
      required:
        - roomName
        - iotVendor
        - deviceConfiguration
      properties:
        roomName:
          type: string
          minLength: 3
          maxLength: 20
          nullable: false
          x-field-extra-annotation: "@NotEmpty"
        iotVendor:
          type: string
          minLength: 3
          maxLength: 20
        deviceType:
          type: string
          minLength: 3
          maxLength: 20
        deviceConfiguration:
          $ref: '#/components/schemas/DeviceConfiguration'
    DeviceType:
      type: string
      enum:
        - "TemperatureSensor"
        - "Blinds"
        - "Light"
        - "Dimmer"
    EatonDataPoint:
      type: integer
      minimum: 1
      maximum: 99
    EatonConfiguration:
      type: object
      properties:
        dataPoint:
          $ref: '#/components/schemas/EatonDataPoint'
        eatonGateway:
          $ref: '#/components/schemas/EatonGateway'
    EatonConfigurationResponse:
      type: object
      properties:
        dataPoint:
          $ref: '#/components/schemas/EatonDataPoint'
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        roomName:
          $ref: '#/components/schemas/RoomName'
    ShellyConfiguration:
      type: object
      properties:
        address:
          type: string
          pattern: '^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$'