name: CI

on:
  push:
    branches: []
  pull_request:
    branches: [ main ]
    types: [ opened ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Discord notification -> success
        uses: sarisia/actions-status-discord@v1
        if: ${{ success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "`CI` `smart-home-sdk`"
      - name: Discord notification -> non success
        uses: sarisia/actions-status-discord@v1
        if: ${{ !success() }}
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "`CI` `smart-home-sdk`"
